/**
 * Shared column definitions for WatermelonDB tables.
 * Keep in sync with Supabase clinical tables used offline.
 */
export type ColType = 'string' | 'number' | 'boolean';

export type ColDef = {
  name: string;
  type: ColType;
  isOptional?: boolean;
  isIndexed?: boolean;
};

const SYNC_META: ColDef[] = [
  { name: 'updated_at', type: 'number' },
  { name: 'created_at', type: 'number' },
  { name: 'deleted_at', type: 'string', isOptional: true, isIndexed: true },
  { name: 'sync_status', type: 'string', isOptional: true },
  { name: 'local_dirty', type: 'number', isOptional: true, isIndexed: true },
];

export const TABLE_DEFS: Record<string, ColDef[]> = {
  patients: [
    { name: 'name', type: 'string' },
    { name: 'age', type: 'number', isOptional: true },
    { name: 'gender', type: 'string', isOptional: true },
    { name: 'condition', type: 'string', isOptional: true },
    { name: 'status', type: 'string', isOptional: true },
    { name: 'risk_level', type: 'string', isOptional: true },
    { name: 'phone_enc', type: 'string', isOptional: true },
    { name: 'image_url', type: 'string', isOptional: true },
    { name: 'ward', type: 'string', isOptional: true, isIndexed: true },
    { name: 'last_visit', type: 'string', isOptional: true },
    { name: 'follow_up_due', type: 'string', isOptional: true },
    { name: 'follow_up_urgent', type: 'number', isOptional: true },
    { name: 'urgency_score', type: 'number', isOptional: true },
    { name: 'assigned_asha_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'assigned_doctor_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'profile_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'abha_id_enc', type: 'string', isOptional: true },
    { name: 'abha_verified', type: 'number', isOptional: true },
    { name: 'date_of_birth', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  referrals: [
    { name: 'patient_id', type: 'string', isIndexed: true },
    { name: 'referred_by', type: 'string' },
    { name: 'referred_to_type', type: 'string' },
    { name: 'referred_to_name', type: 'string', isOptional: true },
    { name: 'reason', type: 'string' },
    { name: 'urgency', type: 'string', isOptional: true },
    { name: 'status', type: 'string', isOptional: true, isIndexed: true },
    { name: 'acknowledged_at', type: 'string', isOptional: true },
    { name: 'completed_at', type: 'string', isOptional: true },
    { name: 'outcome_notes_enc', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  vaccinations: [
    { name: 'patient_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'assigned_asha_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'child_name', type: 'string', isOptional: true },
    { name: 'age_label', type: 'string', isOptional: true },
    { name: 'vaccine_name', type: 'string' },
    { name: 'due_date', type: 'string', isOptional: true },
    { name: 'status', type: 'string', isOptional: true },
    { name: 'administered_at', type: 'string', isOptional: true },
    { name: 'administered_by', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  medical_records: [
    { name: 'patient_id', type: 'string', isIndexed: true },
    { name: 'doctor_id', type: 'string' },
    { name: 'diagnosis', type: 'string', isOptional: true },
    { name: 'prescription_enc', type: 'string', isOptional: true },
    { name: 'notes_enc', type: 'string', isOptional: true },
    { name: 'vitals_json', type: 'string', isOptional: true },
    { name: 'attachments_json', type: 'string', isOptional: true },
    { name: 'erx_json', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  patient_vitals: [
    { name: 'patient_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'profile_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'respiratory_rate', type: 'number', isOptional: true },
    { name: 'heart_rate', type: 'number', isOptional: true },
    { name: 'blood_pressure', type: 'string', isOptional: true },
    { name: 'blood_sugar', type: 'number', isOptional: true },
    { name: 'temperature', type: 'number', isOptional: true },
    { name: 'spo2', type: 'number', isOptional: true },
    { name: 'on_supplemental_oxygen', type: 'number', isOptional: true },
    { name: 'consciousness', type: 'string', isOptional: true },
    { name: 'recorded_at', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  symptom_reports: [
    { name: 'symptom', type: 'string' },
    { name: 'count', type: 'number', isOptional: true },
    { name: 'trend', type: 'string', isOptional: true },
    { name: 'ward', type: 'string', isOptional: true, isIndexed: true },
    { name: 'patient_id', type: 'string', isOptional: true },
    { name: 'reported_by', type: 'string', isOptional: true },
    { name: 'notes_enc', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  community_alerts: [
    { name: 'severity', type: 'string', isOptional: true },
    { name: 'title', type: 'string', isOptional: true },
    { name: 'description', type: 'string', isOptional: true },
    { name: 'ward', type: 'string', isOptional: true },
    { name: 'alert_date', type: 'string', isOptional: true },
    { name: 'icon', type: 'string', isOptional: true },
    { name: 'source', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  dashboard_tasks: [
    { name: 'title', type: 'string', isOptional: true },
    { name: 'subtitle', type: 'string', isOptional: true },
    { name: 'priority', type: 'string', isOptional: true },
    { name: 'icon', type: 'string', isOptional: true },
    { name: 'assigned_to', type: 'string', isOptional: true, isIndexed: true },
    ...SYNC_META,
  ],
  appointments: [
    { name: 'patient_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'doctor_id', type: 'string', isOptional: true, isIndexed: true },
    { name: 'title', type: 'string', isOptional: true },
    { name: 'description', type: 'string', isOptional: true },
    { name: 'appointment_time', type: 'string', isOptional: true },
    { name: 'status', type: 'string', isOptional: true },
    { name: 'duration', type: 'number', isOptional: true },
    { name: 'channel_name', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  campaigns: [
    { name: 'title', type: 'string' },
    { name: 'description', type: 'string', isOptional: true },
    { name: 'ward', type: 'string', isOptional: true },
    { name: 'status', type: 'string', isOptional: true, isIndexed: true },
    { name: 'start_date', type: 'string', isOptional: true },
    { name: 'end_date', type: 'string', isOptional: true },
    { name: 'campaign_date', type: 'string', isOptional: true },
    { name: 'target_count', type: 'number', isOptional: true },
    { name: 'participants_count', type: 'number', isOptional: true },
    { name: 'target_audience', type: 'string', isOptional: true },
    { name: 'created_by', type: 'string', isOptional: true },
    { name: 'published_at', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  pregnancies: [
    { name: 'patient_id', type: 'string', isIndexed: true },
    { name: 'lmp', type: 'string', isOptional: true },
    { name: 'edd', type: 'string', isOptional: true },
    { name: 'gravida', type: 'number', isOptional: true },
    { name: 'para', type: 'number', isOptional: true },
    { name: 'risk_flags_json', type: 'string', isOptional: true },
    { name: 'status', type: 'string', isOptional: true, isIndexed: true },
    { name: 'assigned_asha_id', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  anc_visits: [
    { name: 'pregnancy_id', type: 'string', isIndexed: true },
    { name: 'patient_id', type: 'string', isIndexed: true },
    { name: 'visit_number', type: 'number' },
    { name: 'visit_date', type: 'string', isOptional: true },
    { name: 'findings_enc', type: 'string', isOptional: true },
    { name: 'bp', type: 'string', isOptional: true },
    { name: 'weight', type: 'number', isOptional: true },
    { name: 'hb', type: 'number', isOptional: true },
    { name: 'next_due', type: 'string', isOptional: true },
    { name: 'recorded_by', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  pnc_visits: [
    { name: 'pregnancy_id', type: 'string', isIndexed: true },
    { name: 'patient_id', type: 'string', isIndexed: true },
    { name: 'visit_day', type: 'number' },
    { name: 'visit_date', type: 'string', isOptional: true },
    { name: 'findings_enc', type: 'string', isOptional: true },
    { name: 'mother_well', type: 'number', isOptional: true },
    { name: 'baby_well', type: 'number', isOptional: true },
    { name: 'recorded_by', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  consent_records: [
    { name: 'actor_id', type: 'string', isIndexed: true },
    { name: 'version', type: 'string' },
    { name: 'purposes_json', type: 'string', isOptional: true },
    { name: 'medical_disclaimer', type: 'number', isOptional: true },
    { name: 'privacy_policy', type: 'number', isOptional: true },
    { name: 'data_processing', type: 'number', isOptional: true },
    { name: 'is_minor', type: 'number', isOptional: true },
    { name: 'guardian_name', type: 'string', isOptional: true },
    { name: 'guardian_relationship', type: 'string', isOptional: true },
    { name: 'guardian_acknowledged', type: 'number', isOptional: true },
    { name: 'accepted_at', type: 'string' },
    ...SYNC_META,
  ],
  data_rights_requests: [
    { name: 'actor_id', type: 'string', isIndexed: true },
    { name: 'request_type', type: 'string' },
    { name: 'status', type: 'string', isOptional: true },
    { name: 'payload_json', type: 'string', isOptional: true },
    { name: 'processed_at', type: 'string', isOptional: true },
    ...SYNC_META,
  ],
  audit_log_local: [
    { name: 'actor_id', type: 'string', isOptional: true },
    { name: 'action', type: 'string' },
    { name: 'resource_type', type: 'string' },
    { name: 'resource_id', type: 'string', isOptional: true },
    { name: 'metadata_json', type: 'string', isOptional: true },
    { name: 'created_at', type: 'number' },
    { name: 'updated_at', type: 'number' },
    { name: 'sync_status', type: 'string', isOptional: true },
    { name: 'local_dirty', type: 'number', isOptional: true, isIndexed: true },
  ],
  profiles_local: [
    { name: 'email', type: 'string', isOptional: true },
    { name: 'name', type: 'string', isOptional: true },
    { name: 'role', type: 'string', isOptional: true },
    { name: 'language', type: 'string', isOptional: true },
    { name: 'ward', type: 'string', isOptional: true },
    { name: 'phone_enc', type: 'string', isOptional: true },
    { name: 'updated_at', type: 'number' },
    { name: 'created_at', type: 'number' },
    { name: 'sync_status', type: 'string', isOptional: true },
    { name: 'local_dirty', type: 'number', isOptional: true },
  ],
};

export const WATERMELON_TABLE_NAMES = Object.keys(TABLE_DEFS) as (keyof typeof TABLE_DEFS)[];
