-- ==============================================================================
-- VITAWAVE 2.0 - COMPLETE SUPABASE DATABASE SCHEMA
-- ==============================================================================
-- This script sets up all tables, indexes, and RLS policies required for the 
-- VitaWeave application, including user profiles, patient data, AI insights, 
-- and real-time community health tracking.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. USER PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('asha', 'doctor', 'patient', 'admin')),
    phone TEXT,
    ward TEXT,
    language TEXT DEFAULT 'English',
    avatar_url TEXT,
    level INTEGER DEFAULT 1,
    lives_impacted INTEGER DEFAULT 0,
    hospital_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. HOSPITALS / CLINICS
CREATE TABLE IF NOT EXISTS public.hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT,
    ward TEXT,
    type TEXT DEFAULT 'Government', -- 'Government', 'Private', 'Clinic'
    contact TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Associate profiles with hospitals
ALTER TABLE public.profiles 
ADD CONSTRAINT fk_hospital FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id);

-- 4. PATIENTS
CREATE TABLE IF NOT EXISTS public.patients (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER NOT NULL CHECK (age > 0 AND age < 150),
    gender TEXT CHECK (gender IN ('Male', 'Female', 'Other', 'Not Specified')),
    condition TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Stable' CHECK (status IN ('Active', 'Critical', 'Stable', 'Improving', 'Worsening')),
    risk_level TEXT NOT NULL DEFAULT 'Low' CHECK (risk_level IN ('Low', 'Medium', 'High', 'Critical')),
    phone TEXT,
    image_url TEXT,
    ward TEXT,
    last_visit TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    follow_up_due DATE,
    follow_up_urgent BOOLEAN DEFAULT FALSE,
    assigned_asha_id UUID REFERENCES public.profiles(id),
    assigned_doctor_id UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. MEDICAL RECORDS
CREATE TABLE IF NOT EXISTS public.medical_records (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    doctor_id UUID NOT NULL REFERENCES public.profiles(id),
    diagnosis TEXT NOT NULL,
    prescription TEXT,
    notes TEXT,
    vitals JSONB DEFAULT '{}',
    attachments JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. APPOINTMENTS & TELEMEDICINE
CREATE TABLE IF NOT EXISTS public.appointments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    patient_id UUID NOT NULL REFERENCES public.patients(id),
    doctor_id UUID NOT NULL REFERENCES public.profiles(id),
    title TEXT NOT NULL,
    description TEXT,
    appointment_time TIMESTAMP WITH TIME ZONE NOT NULL,
    duration INTEGER DEFAULT 30, -- minutes
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Active', 'Completed', 'Cancelled', 'No-Show')),
    meeting_link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. AI CHAT HISTORY
CREATE TABLE IF NOT EXISTS public.ai_chat_history (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id),
    patient_id UUID REFERENCES public.patients(id),
    chat_type TEXT NOT NULL CHECK (chat_type IN ('asha_assistant', 'doctor_diagnostics', 'patient_health')),
    messages JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. HEALTH & COMMUNITY ALERTS
CREATE TABLE IF NOT EXISTS public.community_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity TEXT NOT NULL CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    icon TEXT,
    ward TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.weekly_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    time TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. DASHBOARD TASKS
CREATE TABLE IF NOT EXISTS public.dashboard_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    priority TEXT NOT NULL CHECK (priority IN ('urgent', 'today', 'routine')),
    icon TEXT,
    assigned_to UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. COMMUNITY SIGNALS & TRENDS
CREATE TABLE IF NOT EXISTS public.pharmacy_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine TEXT NOT NULL,
    count INTEGER DEFAULT 0,
    max_count INTEGER DEFAULT 100,
    trend TEXT DEFAULT 'stable' CHECK (trend IN ('up', 'down', 'stable')),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.symptom_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symptom TEXT NOT NULL,
    count INTEGER DEFAULT 0,
    trend TEXT DEFAULT 'stable' CHECK (trend IN ('up', 'down', 'stable')),
    ward TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.weekly_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    value INTEGER DEFAULT 0,
    max_value INTEGER DEFAULT 100,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. AI INSIGHTS
CREATE TABLE IF NOT EXISTS public.ai_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('Low', 'Medium', 'High', 'info')),
    action TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. VIDEO CALLS (Log for Agora sessions)
CREATE TABLE IF NOT EXISTS public.video_calls (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    appointment_id UUID REFERENCES public.appointments(id),
    channel_name TEXT NOT NULL,
    host_id UUID NOT NULL REFERENCES public.profiles(id),
    participant_id UUID REFERENCES public.profiles(id),
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    duration INTEGER, -- seconds
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Active', 'Completed', 'Failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. INDEXES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_patients_asha ON public.patients(assigned_asha_id);
CREATE INDEX IF NOT EXISTS idx_patients_doctor ON public.patients(assigned_doctor_id);
CREATE INDEX IF NOT EXISTS idx_medical_records_patient ON public.medical_records(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON public.appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor ON public.appointments(doctor_id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_user ON public.ai_chat_history(user_id);

-- 14. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.symptom_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.video_calls ENABLE ROW LEVEL SECURITY;

-- Shared View Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Public hospitals are viewable by everyone" ON public.hospitals FOR SELECT USING (true);
CREATE POLICY "Public community alerts are viewable by everyone" ON public.community_alerts FOR SELECT USING (true);
CREATE POLICY "Public weekly alerts are viewable by everyone" ON public.weekly_alerts FOR SELECT USING (true);
CREATE POLICY "Public trends are viewable by everyone" ON public.pharmacy_trends FOR SELECT USING (true);
CREATE POLICY "Public symptom reports are viewable by everyone" ON public.symptom_reports FOR SELECT USING (true);
CREATE POLICY "Public weekly trends are viewable by everyone" ON public.weekly_trends FOR SELECT USING (true);
CREATE POLICY "Public AI insights are viewable by everyone" ON public.ai_insights FOR SELECT USING (true);

-- User-specific Policies
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Patients viewable by healthcare workers or self" ON public.patients FOR SELECT USING (
    auth.uid() = id OR 
    auth.uid() = assigned_asha_id OR 
    auth.uid() = assigned_doctor_id OR
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('asha', 'doctor'))
);

CREATE POLICY "Tasks viewable by assigned user or healthcare workers" ON public.dashboard_tasks FOR SELECT USING (
    assigned_to = auth.uid() OR
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('asha', 'doctor'))
);

CREATE POLICY "Medical records viewable by assigned doctor or patient" ON public.medical_records FOR SELECT USING (
    doctor_id = auth.uid() OR 
    patient_id = auth.uid() OR
    EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND (p.assigned_asha_id = auth.uid() OR p.assigned_doctor_id = auth.uid()))
);

-- 15. FUNCTIONS & TRIGGERS FOR UPDATED_AT
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER handle_patients_updated_at BEFORE UPDATE ON public.patients FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER handle_medical_records_updated_at BEFORE UPDATE ON public.medical_records FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER handle_appointments_updated_at BEFORE UPDATE ON public.appointments FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER handle_ai_chat_history_updated_at BEFORE UPDATE ON public.ai_chat_history FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ==============================================================================
-- 16. PHASE 1 — PATIENT HEALTH DATA & CAMPAIGNS
-- ==============================================================================

ALTER TABLE public.patients
ADD COLUMN IF NOT EXISTS profile_id UUID UNIQUE REFERENCES public.profiles(id);

CREATE TABLE IF NOT EXISTS public.patient_vitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    heart_rate INTEGER,
    blood_pressure TEXT,
    blood_sugar NUMERIC,
    temperature NUMERIC,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    recorded_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.patient_medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    schedule TEXT,
    active BOOLEAN DEFAULT TRUE,
    taken_today BOOLEAN DEFAULT FALSE,
    prescribed_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.campaigns (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    location TEXT,
    campaign_date DATE,
    status TEXT DEFAULT 'Planned' CHECK (status IN ('Planned', 'Active', 'Completed', 'Cancelled')),
    target_audience TEXT,
    participants_count INTEGER DEFAULT 0,
    target_count INTEGER DEFAULT 0,
    created_by UUID REFERENCES public.profiles(id),
    ward TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_patients_profile ON public.patients(profile_id);
CREATE INDEX IF NOT EXISTS idx_patient_vitals_profile ON public.patient_vitals(profile_id);
CREATE INDEX IF NOT EXISTS idx_patient_medications_profile ON public.patient_medications(profile_id);

ALTER TABLE public.patient_vitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Patients viewable by healthcare workers or self" ON public.patients;
CREATE POLICY "Patients viewable by healthcare workers or self"
ON public.patients FOR SELECT TO authenticated
USING (
    profile_id = auth.uid()
    OR auth.uid() = assigned_asha_id
    OR auth.uid() = assigned_doctor_id
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
);

CREATE POLICY "Healthcare workers can insert patients"
ON public.patients FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
    OR profile_id = auth.uid()
);

CREATE POLICY "Healthcare workers can update patients"
ON public.patients FOR UPDATE TO authenticated
USING (
    auth.uid() = assigned_asha_id
    OR auth.uid() = assigned_doctor_id
    OR profile_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
);

CREATE POLICY "Users can view own vitals"
ON public.patient_vitals FOR SELECT TO authenticated
USING (
    profile_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
);

CREATE POLICY "Care team can insert vitals"
ON public.patient_vitals FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin', 'patient')
    )
);

CREATE POLICY "Users can view own medications"
ON public.patient_medications FOR SELECT TO authenticated
USING (
    profile_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
);

CREATE POLICY "Healthcare workers can manage medications"
ON public.patient_medications FOR ALL TO authenticated
USING (
    profile_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
)
WITH CHECK (
    profile_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
);

CREATE POLICY "Authenticated users can view campaigns"
ON public.campaigns FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Doctors can manage campaigns"
ON public.campaigns FOR ALL TO authenticated
USING (
    created_by = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('doctor', 'admin')
    )
)
WITH CHECK (
    created_by = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('doctor', 'admin')
    )
);

CREATE TRIGGER handle_patient_medications_updated_at
BEFORE UPDATE ON public.patient_medications
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_campaigns_updated_at
BEFORE UPDATE ON public.campaigns
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ==============================================================================
-- 17. PHASE 2 — AI CHAT HISTORY & MEDICAL RECORDS RLS
-- ==============================================================================

CREATE POLICY "Users can view own chat history"
ON public.ai_chat_history FOR SELECT TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Users can insert own chat history"
ON public.ai_chat_history FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own chat history"
ON public.ai_chat_history FOR UPDATE TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Users can delete own chat history"
ON public.ai_chat_history FOR DELETE TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Medical records viewable by assigned doctor or patient" ON public.medical_records;
CREATE POLICY "Medical records viewable by care team"
ON public.medical_records FOR SELECT TO authenticated
USING (
    doctor_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id = patient_id AND p.profile_id = auth.uid()
    )
    OR EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id = patient_id
        AND (p.assigned_asha_id = auth.uid() OR p.assigned_doctor_id = auth.uid())
    )
);

CREATE POLICY "Doctors can insert medical records"
ON public.medical_records FOR INSERT TO authenticated
WITH CHECK (
    doctor_id = auth.uid()
    AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('doctor', 'admin')
    )
);

CREATE POLICY "Doctors can update own medical records"
ON public.medical_records FOR UPDATE TO authenticated
USING (doctor_id = auth.uid());

CREATE POLICY "Users can view relevant appointments"
ON public.appointments FOR SELECT TO authenticated
USING (
    doctor_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id = patient_id AND p.profile_id = auth.uid()
    )
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'admin')
    )
);

CREATE POLICY "Doctors can manage appointments"
ON public.appointments FOR ALL TO authenticated
USING (
    doctor_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('doctor', 'admin')
    )
)
WITH CHECK (
    doctor_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('doctor', 'admin', 'patient')
    )
);

-- ==============================================================================
-- 18. PHASE 4 — VACCINATIONS & TASK SCOPING
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.vaccinations (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    patient_id UUID REFERENCES public.patients(id) ON DELETE SET NULL,
    child_name TEXT NOT NULL,
    age_label TEXT,
    vaccine_name TEXT NOT NULL,
    due_date DATE,
    status TEXT NOT NULL DEFAULT 'due' CHECK (status IN ('due', 'completed')),
    administered_at TIMESTAMP WITH TIME ZONE,
    administered_by UUID REFERENCES public.profiles(id),
    assigned_asha_id UUID REFERENCES public.profiles(id),
    ward TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vaccinations_asha ON public.vaccinations(assigned_asha_id);
CREATE INDEX IF NOT EXISTS idx_vaccinations_patient ON public.vaccinations(patient_id);
CREATE INDEX IF NOT EXISTS idx_vaccinations_status ON public.vaccinations(status);

ALTER TABLE public.vaccinations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Healthcare workers can view vaccinations"
ON public.vaccinations FOR SELECT TO authenticated
USING (
    assigned_asha_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id = patient_id AND p.profile_id = auth.uid()
    )
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'doctor', 'admin')
    )
);

CREATE POLICY "ASHA workers can manage vaccinations"
ON public.vaccinations FOR ALL TO authenticated
USING (
    assigned_asha_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'admin')
    )
)
WITH CHECK (
    assigned_asha_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('asha', 'admin')
    )
);

CREATE TRIGGER handle_vaccinations_updated_at
BEFORE UPDATE ON public.vaccinations
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP POLICY IF EXISTS "Tasks viewable by assigned user or healthcare workers" ON public.dashboard_tasks;
CREATE POLICY "Dashboard tasks viewable by care team"
ON public.dashboard_tasks FOR SELECT TO authenticated
USING (
    assigned_to IS NULL
    OR assigned_to = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role IN ('doctor', 'admin')
    )
);
